import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/context/Provider";
import { Header } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: Readonly<{
  session: never;
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider session={session}>
        <body className="w-full h-full overflow-x-hidden">
          <Header />
          <div className="w-full h-screen overflow-x-hidden">{children}</div>
          <div className="w-full" id="modal" />
        </body>
      </Provider>
    </html>
  );
}
